### ISSUE TITLE
list_storage_files recursive = FALSE does not work

### ISSUE THREAD

**Issue by nlneas1** [Azure/AzureStor#45]
I am trying to list the folders within a specific container using the following code

```r
AzureStor::list_storage_files(
  containers[["data"]],
  dir = "path/to/folder",
  recursive = FALSE,
  info = "name"
)
```

However the `recursive = FALSE` option seems to have no effect and presents the file paths for all files in each of the folders (i.e. `recursive = TRUE`).

Looking into this, I cannot see where `recursive` is used within `list_blobs()` even though it is an option to that function.

**Comment by Hong-Revo** [comment]
Hi, I guess you're using blobs although the code references `list_azure_files`.

Blob storage is interesting, because it doesn't actually have directories: they're just mocked up using filenames that contain "/". So any call to the REST API will always return all files, and it's the job of the client to parse those filenames and organise them into a hierarchy.

The `recursive` arg to `list_blobs` is basically for consistency with the other storage types (`list_azure_files` and `list_adls_files`) which do support directories. Since blob/ADLS interop is now generally available, if you want true directory support, consider using the ADLS API to access your blob containers. It's basically as simple as replacing "blob" with "dfs" in the storage URL in your call to `storage_endpoint`.

**Comment by nlneas1** [comment]
Ah, sorry, it was supposed to be `list_storage_files()`. Essentially I am trying to list the directories. Hence why I do not wish to use `recursive = TRUE` (the default from what I can tell).

I will give what you suggested a try.
