### ISSUE TITLE
Support for append/edit content to existing files

### ISSUE THREAD

**Issue by yorjaggy** [Azure/AzureStor#61]
Hi there! 

First of all thanks for this great work in the AzureR package, I'm using actively AzureStor and your package works awesome. Looking at the documentation there are no details about editing or appending content to a file already located in a Storage Container. 

My current use case is to save logs in Azure Storage. Is it possible to consider this enhancement? On the contrary case, do you consider there is any workaround for this case in the current AzureStor?

Thank you! :nerd_face: 

Yor Castaño

**Comment by hongooi73** [comment]
Storage has append blobs, which are a different type to the regular block blobs. This can be added as something for AzureStor to support.

**Comment by yorjaggy** [comment]
Awesome! Thanks for your quick reply.

Is there any restriction or detailed guideline to write some contributions to AzureStor?

**Comment by hongooi73** [comment]
There are no real restrictions, you just have to sign the Contributor License Agreement (CLA) and follow the code of conduct -- fairly standard stuff. See [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md).

If you want to make a PR, I'd suggest looking at the code in [blob_transfer_internal.R](https://github.com/Azure/AzureStor/blob/master/R/blob_transfer_internal.R) and modifying `upload_blob_internal` to handle append blobs.

In terms of style, just follow the style of the current code:
- 4 spaces per tab
- opening brace on a newline
- no braces necessary for one-line if-else statements
- no spaces in named arguments for function calls, ie `f(x=42, y="bar")` instead of `f(x = 42, y = "bar")`
- max 120 characters per line

Thanks!

**Comment by hongooi73** [comment]
Storage API documentation for appending: https://docs.microsoft.com/en-us/rest/api/storageservices/append-block

**Comment by hongooi73** [comment]
Now implemented in #71
